%%% compareStatsAge.m
%%% This function calculates the correlation and p-value of various organization
%%% parameters for various groups of animals using the Spearman Rank Correlation.
%%%
%%% Input Arguments
%%% statsFile = the name of an output file generated by MTQuant.
%%% groups (optional) = a list of group numbers to compare. These are the values of the DirNum
%%%      column of the output file (see Section 4 of the MTQuant documentation
%%%      for more information). If groups is not inputted, or it is empty (i.e.
%%%      groups=[];), the function compares all groups.
%%% stats (optional) = list of columns in statsFile for which to calculate the cor-
%%%      relation. This can be a list of column numbers or a list of
%%%      strings, where each string is the column name (See Section 5.2
%%%      of MTQuant documentation for complete list). By default, stats =
%%%      {'Avg Spacing','Std Dev Spacing','Avg Coverage','Avg Length'};
%%% 
%%% Output Arguments
%%% allRhos = cell array with Spearman Rank Correlation for parameters in stats
%%% allPs = cell array containing the p-values associated with allRhos

function [allRhos,allPs]= compareStatsAge(statsFile,groups,stats)

T = readtable(statsFile);
C = table2cell(T);

dirNums = cell2mat(C(:,3));
uDirNums = unique(dirNums);
dirCounts = hist(dirNums,uDirNums);

[uFolderNames,~,~] = getFolderNamesFromTable(C(:,1),dirNums);
varNames = T.Properties.VariableNames;

if ~exist('groups','var') || isempty(groups)
    groups = uDirNums;
end

if iscellstr(groups)
    dirsToCompare = find(ismember(uFolderNames,groups));
else
    dirsToCompare = groups;
end

if ~exist('stats','var') || isempty(stats)
    stats = {'Avg_Spacing','Std_Dev_Spacing','Avg_Coverage','Avg_Length'};
    statsToCompare = find(ismember(varNames,stats));
elseif iscellstr(stats)
    statsToCompare = find(ismember(varNames,stats));
else
    statsToCompare = stats;
end

dirsToCompare(dirCounts(dirsToCompare)<4) = [];

numStats = length(statsToCompare);

allPs = cell(2,numStats);
allRhos = cell(2,numStats);

for k = 1:numStats
    statInd = statsToCompare(k);
    allPs(1,k) = varNames(statInd);
    allRhos(1,k) = varNames(statInd);
    
    currStats = cell2mat(C(ismember(dirNums,dirsToCompare),statInd));
    currDirs = dirNums(ismember(dirNums,dirsToCompare));
    toRemove = ~isfinite(currStats);
    currStats(toRemove) = [];
    currDirs(toRemove) = [];
    [rho,p] = corr(currStats,currDirs,'type','Spearman');
    
    allRhos(2,k) = {rho};
    allPs(2,k) = {p};
    
end
